version: "3.1"
services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    links:
      - jenkins
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /mnt/pidata/jenkins_home:/var/jenkins_home