version: "3.1"
services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/web:/web"
    ports:
      - "80:80"
  intellij:
    build: ./intellij
    restart: always
    ports: 
      - "1017:1017"
  zumrud:
    build: ./zumrud
    restart: always
    volumes:
      - "./zumrud:/app"
    ports:
      - "3000:3000"
    